# Generated by Django 4.2.27 on 2025-12-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodunit',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='bloodunit',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bloodunit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=3),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='units_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
