# Generated by Django 4.2.27 on 2025-12-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_remove_bloodunit_blood_type_remove_bloodunit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
